title: Portafolio de Proyectos
author: Fernando Cuevas
email: luisfernandocuevas@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  En esta página me gustaría tener:
    · Mi Curriculum Vitae
    · Una Pestaña de Formula SAE
      ~ Business Presentation de UNAM Motorsports
    · Una Pestaña de Ingeniería de Diseño
      ~ Diseño CAD de reciclador de residuos
      ~ Diseño CAD/CAE de DRON
    · Una pestaña de Sustentabilidad
      ~ Proyecto de Brazil
      ~ Proyecto de Morelos
      ~ Proyecto de Páneles Solares
      ~ Proyecto de Exportación
    · Una pestaña de Ciencia de Datos
    · Una pestaña de Certificados
    · Una pestaña de Vida Personal
      ~ Libros leidos
      ~ Maratones
      ~ Proyectos de Edición
      ~ About me
    

# social links
twitter_username: Fer_Cuevas27 # DO NOT include the @ character, or else the build will fail!
github_username:  FerCuevas27 # DO NOT include the @ character, or else the build will fail!
Linkedin_username: https://www.linkedin.com/in/luis-fernando-cuevas/ 

show_excerpts: true # set to false to remove excerpts on the homepage
