theme: minima
title: Portafolio de Proyectos
author: Fernando Cuevas
email: luisfernandocuevas@outlook.com
description: > # this means to ignore newlines until "baseurl:"
Ingeniería Mecatrónica
Facultad de Ingeniería, UNAM

# social links
twitter_username: Fer_Cuevas27 # DO NOT include the @ character, or else the build will fail!
github_username:  FerCuevas27 # DO NOT include the @ character, or else the build will fail!
Linkedin_username: https://www.linkedin.com/in/luis-fernando-cuevas/ 

show_excerpts: true # set to false to remove excerpts on the homepage
